# Generated by Django 5.2.7 on 2025-10-27 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('pack_type', models.CharField(max_length=100)),
                ('ppg', models.CharField(max_length=100)),
                ('pack_size', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('date', models.DateField()),
                ('br_cat_id', models.CharField(max_length=100)),
                ('sales_value', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_units', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('d1', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('d2', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('d3', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('d4', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('d5', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('d6', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av1', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av2', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av3', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av4', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av5', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('av6', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev1', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev2', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev3', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev4', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev5', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('ev6', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_data',
                'indexes': [models.Index(fields=['brand'], name='sales_data_brand_841381_idx'), models.Index(fields=['pack_type'], name='sales_data_pack_ty_e68ae3_idx'), models.Index(fields=['ppg'], name='sales_data_ppg_105f3d_idx'), models.Index(fields=['channel'], name='sales_data_channel_9664cf_idx'), models.Index(fields=['year'], name='sales_data_year_4512f9_idx'), models.Index(fields=['month'], name='sales_data_month_625238_idx'), models.Index(fields=['date'], name='sales_data_date_b95148_idx')],
            },
        ),
    ]
